A new study created in RDB with name: MLP_114817
Trial 0 finished with value: 1658.7120938378043 and parameters: {'input_dropout': 0.05, 'hidden_layers': 4, 'hidden_units': 224, 'kernel_initializer': 'he_uniform', 'hidden_activation': 'prelu', 'hidden_dropout': 0.25, 'batch_norm': 'off', 'optimizer_type': 'rmsprop', 'lr': 9.150326047440301e-05, 'batch_size': 96}. Best is trial 0 with value: 1658.7120938378043.
Trial 1 finished with value: 133.44858382155377 and parameters: {'input_dropout': 0.05, 'hidden_layers': 5, 'hidden_units': 96, 'kernel_initializer': 'he_normal', 'hidden_activation': 'leaky_relu', 'hidden_dropout': 0.15000000000000002, 'batch_norm': 'on', 'optimizer_type': 'rmsprop', 'lr': 0.0053763525659945785, 'batch_size': 64}. Best is trial 1 with value: 133.44858382155377.
Trial 2 failed because of the following error: ValueError('Input contains NaN.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
  File "/tmp/ipykernel_102620/2376586184.py", line 60, in __call__
    scores.append(mean_squared_error(validate_objective_variable, validate_pred))
  File "/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_regression.py", line 442, in mean_squared_error
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
  File "/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_regression.py", line 102, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py", line 899, in check_array
    _assert_all_finite(
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py", line 146, in _assert_all_finite
    raise ValueError(msg_err)
ValueError: Input contains NaN.
