A new study created in RDB with name: MLP_84617
Trial 0 finished with value: 106.78376130222989 and parameters: {'input_dropout': 0.2, 'hidden_layers': 4, 'hidden_units': 224, 'kernel_initializer': 'random_normal', 'hidden_activation': 'relu', 'hidden_dropout': 0.1, 'batch_norm': 'on', 'optimizer_type': 'sgd', 'lr': 0.0005322547994555062, 'batch_size': 96}. Best is trial 0 with value: 106.78376130222989.
Trial 1 finished with value: 307.96533539711186 and parameters: {'input_dropout': 0.15000000000000002, 'hidden_layers': 2, 'hidden_units': 128, 'kernel_initializer': 'he_normal', 'hidden_activation': 'prelu', 'hidden_dropout': 0.25, 'batch_norm': 'off', 'optimizer_type': 'sgd', 'lr': 1.7260447941380813e-05, 'batch_size': 96}. Best is trial 0 with value: 106.78376130222989.
Trial 2 finished with value: 418.22833894922974 and parameters: {'input_dropout': 0.1, 'hidden_layers': 3, 'hidden_units': 64, 'kernel_initializer': 'random_normal', 'hidden_activation': 'relu', 'hidden_dropout': 0.25, 'batch_norm': 'off', 'optimizer_type': 'rmsprop', 'lr': 7.603027137944198e-05, 'batch_size': 64}. Best is trial 0 with value: 106.78376130222989.
Trial 3 finished with value: 1417.2803775222517 and parameters: {'input_dropout': 0.0, 'hidden_layers': 5, 'hidden_units': 256, 'kernel_initializer': 'random_normal', 'hidden_activation': 'prelu', 'hidden_dropout': 0.3, 'batch_norm': 'on', 'optimizer_type': 'sgd', 'lr': 1.7992953400309685e-05, 'batch_size': 64}. Best is trial 0 with value: 106.78376130222989.
Trial 4 failed because of the following error: ValueError("Input contains infinity or a value too large for dtype('float32').")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
  File "/tmp/ipykernel_102620/2662274010.py", line 57, in __call__
    scores.append(mean_squared_error(validate_objective_variable, validate_pred))
  File "/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_regression.py", line 442, in mean_squared_error
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
  File "/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_regression.py", line 102, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py", line 899, in check_array
    _assert_all_finite(
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py", line 146, in _assert_all_finite
    raise ValueError(msg_err)
ValueError: Input contains infinity or a value too large for dtype('float32').
